### ISSUE TITLE
[autoendpoint] A "User Unknown" or "User Unregistered" type response from bridge should delete a UAID

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#190] opened 2020-07-17 21:48 UTC
For parity with https://github.com/mozilla-services/autopush/pull/1415, 

If a bridge system reports that a user is "gone" or "unregistered" (via either the body or a 404/410 response) we should presume that the UAID is no longer accessible and drop the UAID. Since mobile devices will not share connections, this should be fine. It will mean that older installs of fennec will no longer have active subscriptions, but as a bonus, if they ever try to establish one, their UAID would be considered invalid which would cause the endpoints to potentially be refreshed anyway.

**Comment by Mcat12** [comment] 2020-07-20 17:33
Duplicate of #173

**Closed by Mcat12** 2020-07-20 17:33 UTC
Labels: 5
