### ISSUE TITLE
Drop "webpush" Router entries that have not connected within 60 days

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush-rs#223] opened 2020-08-17 22:58 UTC
Create an operational script that purges the router table of any device that has not connected to the service in 60 days.

This mimics the original purge that would take place as part of message table rotation.

**Comment by pjenvey** [comment] 2022-02-18 19:51
Dupe of #224

**Closed by pjenvey** 2022-02-18 19:51 UTC
Labels: 3, cleanup
